//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.20 at 08:35:55 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mnb.hu/webservices/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package wsdl;
